export const t = {
  appName: "AC7 Group",
  appSubtitle: "Aragti Cad — Kaydka Kooxda",
  nav: {
    dashboard: "Dashboard-ka",
    members: "Xubnaha",
    calendar: "Kalandarka",
    timeline: "Taariikhda",
    myStatement: "Warbixintayda",
    profile: "Profile-kayga",
    admin: "Maamulka",
  },
  dashboard: {
    title: "Dashboard-ka",
    subtitle: "Dulmar guud oo kaydka kooxda AC7",
    totalSavings: "Wadarta Kaydka",
    totalDebt: "Wadarta Deynta",
    members: "Xubnaha",
    monthlyFee: "Lacagta Bishii",
    savingsGrowth: "Koritaanka Kaydka",
    recentPayments: "Lacag Bixinnadii Ugu Dambeeyay",
    noPayments: "Weli lacag bixin ma jirto",
    monthsElapsed: "Bilaha La Soo Dhaafay",
    groupGoal: "Hadafka Kooxda",
    goalProgress: "Horumarka Hadafka",
    savingsRecords: "kayd",
    cloudData: "Xogta Firebase (savings)",
  },
  members: {
    title: "Xubnaha",
    subtitle: "Xubnaha kooxda AC7 iyo qaybtooda",
    addMember: "Ku Dar Xubin",
    nameRequired: "Magaca xubinta waa lagama maarmaan",
    namePlaceholder: "Magaca buuxa",
    deleteMember: "Tirtir",
    totalPaid: "Wadarta La Bixiyay",
    debt: "Deynta",
    share: "Qaybta (%)",
    ownership: "Hantida",
    joinDate: "Taariikhda Ku Biiray",
    endDate: "Taariikhda Dhamaadka",
    paid: "Bixiyay ✓",
    unpaid: "Ma Bixin ✗",
    noMembers: "Weli xubno ma jiraan",
    confirmDelete: "Ma hubtaa inaad xubintan ugu wareejiso kaydka (Bin)? Macluumaadkeeda waa la kaydin doonaa.",
    memberAdded: "Xubinta si guul leh ayaa loo daray",
    memberDeleted: "Xubinta waa lagu wareejiyay kaydka (Bin)",
    memberUpdated: "Xubinta waa la cusboonaysiiyay",
    name: "Magaca",
    phone: "Telefoonka",
    phonePlaceholder: "Geli telefoonka",
    monthsPaid: "Bilaha La Bixiyay",
    currentDue: "Lacagta Bishan",
    example: "Tusaale: 5 bil × $55 = qaybta kooxda",
  },
  calendar: {
    title: "Kalandarka",
    subtitle: "Arag malinta iyo saacada lacag bixinta",
    prevYear: "Sannadkii Hore",
    nextYear: "Sannadka Xiga",
    prevMonth: "Bishii Hore",
    nextMonth: "Bisha Xigta",
    today: "Maanta",
    noPayments: "Ma jiro lacag bixin",
    paidOn: "wuxuu bixiyay",
    at: "saacadu",
    day: "Maalin",
  },
  ledger: {
    title: "Diiwaanka",
    subtitle: "Calaamadee lacag bixinta xubnaha",
    enterPin: "Geli PIN-ka Maamulka",
    pinPlaceholder: "Geli PIN-ka",
    pinRequired: "PIN-ka waa lagama maarmaan",
    pinIncorrect: "PIN-ka waa khaldan yahay",
    unlock: "Fur Maamulka",
    tickPayment: "✅ Calaamadee",
    paymentTicked: "Lacag bixinta waa la diiwaangeliyay",
    alreadyPaid: "Bishan horey ayuu u bixiyay",
    member: "Xubinta",
    status: "Xaaladda",
    amount: "Qadarka",
    month: "Bisha",
    action: "Ficil",
    allPaid: "Dhammaan xubnaha way bixiyeen bishan!",
    escalated: "Lacagta ayaa kordhay (deyn)",
    thisMonth: "Bishan",
    nextMonth: "Bisha xigta",
    feeDoubleHint: "Haddii aadan bixin → bisha xigta labanlaab",
    undoPayment: "Dib u noqo",
    confirmUndo: "Ma hubtaa inaad ka laabato bixinta {name} bishan?",
    paymentUndone: "Bixinta waa la ka laabtay",
    paymentNotFound: "Lacag bixinta bishan lama helin",
  },
  timeline: {
    title: "Taariikhda",
    subtitle: "Dhammaan lacag bixinnada kooxda",
    noEvents: "Weli wax dhacdo ah ma jiro",
    paidBy: "waxaa bixiyay",
    forMonth: "bishii",
  },
  myStatement: {
    title: "Warbixintayda",
    subtitle: "Soo dejiso PDF-kaaga warbixinta",
    selectMember: "Dooro Magacaaga",
    chooseName: "-- Dooro magacaaga --",
    yourStats: "Xogtaada",
    totalPaid: "Wadarta Aad Bixisay",
    yourShare: "Qaybtaada Kooxda",
    yourDebt: "Deyntaada",
    monthsPaid: "Bilaha Aad Bixisay",
    downloadPdf: "Soo Dejiso PDF",
    shareWhatsapp: "Wadaag WhatsApp",
    shareOther: "Wadaag Apps Kale",
    pdfReady: "PDF-kaaga waa diyaar",
    pdfDownloaded: "PDF-ka waa la soo dejiyay",
    noMember: "Fadlan soo gal si aad u aragto warbixintaada",
    newAccountHint: "Koonto cusub — PDF-kaaga waa diyaar xitaa haddii aadan weli wax bixin",
    statementTitle: "Warbixin Maaliyadeed",
  },
  admin: {
    title: "Maamulka AC7",
    desc: "Geli PIN-ka maamulka si aad u furto",
    settings: "Dejinta",
    ledger: "Diiwaanka",
    editTable: "Xubnaha",
    saveAll: "Kaydi Dhammaan",
    saved: "Wax walba waa la kaydiyay",
    groupGoal: "Hadafka Guud",
    monthlyFee: "Lacagta Bishii ($)",
    startDate: "Taariikhda Bilowga",
    reminderDay: "Maalinta Xusuusinta (15)",
    lateFee: "Kordhinta Deynta (Auto)",
    lateFeeDesc: "Hadii uusan bixin → bisha xigta $110, $165...",
    memberTable: "Jadwalka Xubnaha",
    lockAdmin: "Xir Maamulka",
    adminOnly: "Maamulka Kaliya",
    status: "Xaaladda",
    login: "Login",
    active: "Active",
    inactive: "Inactive",
    loginActivated: "Login-ka waa la active gareeyay",
    loginDeactivated: "Login-ka waa la xiray",
    loginId: "Login ID",
    loginIdPlaceholder: "magac@ac7.group",
    loginIdNewPlaceholder: "tusaale: ahmed",
    loginIdInvalidNew: "Login ID waa inuu ugu yaraan 2 xaraf yahay (tusaale: ahmed)",
    addMemberHint: "Ku dar xubin cusub — Firebase Auth + Firestore hal mar",
    addMemberDialogDesc: "Login ID + password ayaa Firebase Auth u abuuraya. Xogta waxay ku kaydsan tahay Firestore.",
    authEmailPreview: "Auth email",
    paid: "Bixiyay",
    paidYes: "Haa",
    paidNo: "Maya",
    passwordMinLength: "Password waa inuu ugu yaraan 6 xaraf yahay",
    contributionRequired: "Lacagta bishii waa lagama maarmaan",
    newPassword: "Password",
    newPasswordPlaceholder: "Password cusub...",
    loginIdRequired: "Login ID u samee (waa inuu @ leeyahay)",
    passwordRequired: "Password u samee marka hore, kadibna kaydi",
    loginIdInvalid: "Login ID waa inuu @ leeyahay (tusaale: ali@ac7.group)",
    loginIdTaken: "Login ID-kan horey ayaa loo isticmaalay",
    loginSetupHint: "1) Login ID + Password qor  2) Guji Active (auto kaydin)",
    saveAndActivate: "Kaydi & Active",
    bin: "Kaydka (Bin)",
    loginArchived: "Login-ka waa la xiray (kaydka)",
    loginStatus: "Xaaladda Login-ka",
    binTitle: "Xubnaha La Saaray",
    binSubtitle: "Xubnaha la saaray waxay halkan ku kaydsan yihiin. Waxaad dib ugu soo celin kartaa kooxda.",
    binEmpty: "Kaydka waa madhan — xubin la saaray ma jirto",
    archivedAt: "Taariikhda La Saaray",
    archivedReason: "Sababta",
    reasonAuto: "Si toos ah (4 bil ma bixin)",
    reasonAdmin: "Admin ayaa saaray",
    paymentsSaved: "Lacag bixinnada la kaydiyay",
    chatsSaved: "Fariimaha la kaydiyay",
    restore: "Dib u soo celi",
    confirmRestore: "Ma hubtaa inaad {name} dib ugu soo celiso kooxda?",
    restored: "{name} waa dib loogu soo celiyay kooxda",
    viewDetails: "Arag faahfaahinta",
    hideDetails: "Qari faahfaahinta",
  },
  login: {
    subtitle: "Geli si aad u gasho AC7 Group",
    identifier: "Login ID",
    identifierPlaceholder: "admin ama Ghaalabh10@gmail.com",
    email: "Login ID",
    password: "Password",
    submit: "Soo Gal",
    logout: "Ka Bax",
    adminNote: "Login-ka waxaa active gareeyaa admin-ka kaliya.",
  },
  profile: {
    title: "Profile",
    myProfile: "Macluumaadkaaga",
    monthlyRequired: "Lacagta Bishii",
    annualTarget: "Hadafka Sannadlaha",
    annualProgress: "Horumarka Sannadlaha",
    lastWarning: "⚠️ DIGNIIN UGU DAMBEYSAY — 3 bil ma bixin!",
    warningDesc: "Bisha 4aad hadii aadan bixin, si toos ah ayaa lagaa saarayaa kooxda.",
    removedDesc: "Waxaa lagaa saaray kooxda sababtoo ah 4 bil oo xiriir ah aadan bixin. La xiriir admin-ka.",
    chat: "Chat Admin",
    noChat: "Weli fariin ma jirto",
    chatPlaceholder: "Qor fariin...",
    deleteChat: "Tirtir fariinta",
    confirmDeleteChat: "Ma hubtaa inaad tirtirto farintan?",
    chatDeleted: "Fariinta waa la tirtiray",
    changePhoto: "Beddel sawirka",
    removePhoto: "Ka saar sawirka",
    photoUpdated: "Sawirka profile-ka waa la cusboonaysiiyay",
    photoRemoved: "Sawirka waa la saaray",
    notFound: "Xubinta lama helin",
    currentMonth: "Bishan",
    paidThisMonth: "Bixiyay bishan ✓",
    unpaidThisMonth: "Ma bixin bishan ✗",
    nextMonthDue: "Lacagta bisha xigta",
    lastPayment: "Bixintii ugu dambeysay",
  },
  announcements: {
    title: "Ogeysiisyada",
    message: "Fariintaada",
    placeholder: "Qor ogeysiiskaaga halkan...",
    duration: "Mudo (saacado)",
    durationHint: "Inta saacadood ee ogeysiisku muuqan doono app-ka gudahiisa",
    post: "Dir Ogeysiis",
    posted: "Ogeysiiska waa la diray!",
  },
  recovery: {
    title: "Soo Kabashada PIN-ka",
    desc: "5 jeer PIN khaldan. Code ayaa loo diray:",
    sendCode: "Dir Code Gmail-ka",
    enterCode: "Geli Code-ka Gmail-ka",
    verify: "Xaqiiji Code-ka",
    success: "Maamulka waa la furay!",
    invalidCode: "Code-ka waa khaldan yahay",
    lockedOut: "PIN-ka waa xiran. Isticmaal Gmail recovery.",
  },
  reminder: {
    title: "Xusuusin Bishii",
    message: "Bishan waa maalinta 15-aad! Fadlan xaqiiji in lacagta $55 lagu shubay account-ka.",
    dismiss: "Xir",
  },
  settings: {
    title: "Dejinta",
    subtitle: "Dejinta buuxda ee kooxda AC7",
    groupInfo: "Macluumaadka Kooxda",
    monthlyFee: "Lacagta Bishii",
    startDate: "Taariikhda Bilowga",
    adminPin: "PIN-ka Maamulka",
    adminEmail: "Gmail-ka Maamulka",
    systemStatus: "Xaaladda System-ka",
    connected: "Ku xiran (Firebase)",
    demo: "Habka Demo (Local)",
  },
  common: {
    save: "Kaydi",
    cancel: "Jooji",
    confirm: "Xaqiiji",
    delete: "Tirtir",
    edit: "Tafatir",
    loading: "Maamulka ayaa backgroundka shaqo ka wado.",
    busy: "Waa la kaydinayaa...",
    error: "Khalad ayaa dhacay",
    success: "Guul!",
    close: "Xir",
    search: "Raadi",
    currency: "$",
    year: "Sannad",
    month: "Bil",
    more: "Kale",
  },
  pwa: {
    installTitle: "Ku rakib AC7 Group telefoonkaaga",
    installDesc: "Isticmaal sida app dhab ah — telefoon iyo laptop labadaba",
    installBtn: "Ku rakib App-ka",
    later: "Hadhow",
    iosHint: "Safari → Share",
    iosHint2: "→ Add to Home Screen",
  },
} as const;
